### ISSUE TITLE
Compile error

### ISSUE THREAD

**Issue by sereres** [iLCSoft/MarlinDD4hep#1]
Compiling as is results in the following error when building InitializeDD4hep.cc.o:

usr@comp:~/MarlinDD4hep_build$ make install
[ 50%] Building CXX object CMakeFiles/MarlinDD4hep.dir/src/InitializeDD4hep.cc.o

MarlinDD4hep/src/InitializeDD4hep.cc: In member function ‘virtual void InitializeDD4hep::init()’:
MarlinDD4hep/src/InitializeDD4hep.cc:65:82: error: passing ‘const string {aka const std::__cxx11::basic_string<char>}’ as ‘this’ argument discards qualifiers [-fpermissive]
     ILDCellID0::encoder_string = lcdd.constantAsString( _encodingStringParameter );

This can be downgraded to a warning by forcibly passing the -fpermissive flag to the compiler, and then the library will successfully install. 

Either the error should be fixed, or the CMake options in CMakeLists should automatically add this flag.

**Comment by andresailer** [comment]
You need to update LCIO.

**Comment by andresailer** [comment]
If this problem doesn't disappear when upgrading LCIO, please re-open or create a new issue
